apiVersion: v1
kind: Service
metadata:
  name: shoplite
  labels:
    app.kubernetes.io/name: shoplite
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: shoplite
  ports:
    - name: http
      port: 80
      targetPort: http
